@host_aws = https://addr-clns.pilotworks.live
@host_local = http://127.0.0.1:3000
@host={{host_local}}

### Generate Addresses
POST {{host}}/gen HTTP/1.1
content-type: application/json
User-Agent: rest-client
auth: aaa

{
    "address_in": "Canadian",
    "format": "JSON",
    "language": "in English"
}