@host_aws = https://addr-clns.pilotworks.live
@host_local = http://127.0.0.1:3000
@host={{host_local}}

### Generate Addresses
POST {{host}}/gen HTTP/1.1
content-type: application/json
User-Agent: rest-client
auth: dgf834-20230830

{
    "address_in": "Chinese",
    "format": "JSON",
    "language": "in Chinese"
}

### Cleanse Addresses
POST {{host}}/cleanse/gpt HTTP/1.1
content-type: application/json
User-Agent: rest-client
Accept-Encoding: *
auth: dgf834-20230830

{
    "params": {
        "translate_output": "false"
    },
    "addresses": 
    {
        "1":"123 Main St, ON, Toronto, Canada, M5V 2B7",
        "2":"V6G 1C4 789 Elm St, Apt 456, Vancouver, BC",
        "3":"To Steve Montreal QC 567 Apple St Canada H3B 1C8",
        "4":"987 Maple St Calgary AB",
        "5":"Oak 654 Ottawa Ontario K1N 5W5 Canada"
    }
    # {
    #     "1": "北京市朝阳区建国门外大街10号院",
    #     "2": "四川省成都市武侯区天府大道中段",
    #     "3": "广东省深圳市福田区华强北路",
    #     "4": "江苏省南京市鼓楼区中山东路",
    #     "5": "山东省青岛市市南区香港中路"
    # }
}